import sys
import struct
import json

struct_fmt = '>6c2s3s2s2s2s2s2s2B5c2s2c'
struct_len = struct.calcsize(struct_fmt)
struct_unpack = struct.Struct(struct_fmt).unpack_from
boxPokemon = []

# extracted name tables
pokemonNames = [ # from pokeorange/data/pokemon_names.asm
"?????@@@@@",
"BULBASAUR@",
"IVYSAUR@@@",
"VENUSAUR@@",
"CHARMANDER",
"CHARMELEON",
"CHARIZARD@",
"SQUIRTLE@@",
"WARTORTLE@",
"BLASTOISE@",
"CATERPIE@@",
"METAPOD@@@",
"BUTTERFREE",
"WEEDLE@@@@",
"KAKUNA@@@@",
"BEEDRILL@@",
"PIDGEY@@@@",
"PIDGEOTTO@",
"PIDGEOT@@@",
"RATTATA@@@",
"RATICATE@@",
"SPEAROW@@@",
"FEAROW@@@@",
"EKANS@@@@@",
"ARBOK@@@@@",
"PIKACHU@@@",
"RAICHU@@@@",
"SANDSHREW@",
"SANDSLASH@",
"NIDORAN♀@@",
"NIDORINA@@",
"NIDOQUEEN@",
"NIDORAN♂@@",
"NIDORINO@@",
"NIDOKING@@",
"CLEFAIRY@@",
"CLEFABLE@@",
"VULPIX@@@@",
"NINETALES@",
"JIGGLYPUFF",
"WIGGLYTUFF",
"ZUBAT@@@@@",
"GOLBAT@@@@",
"ODDISH@@@@",
"GLOOM@@@@@",
"VILEPLUME@",
"PARAS@@@@@",
"PARASECT@@",
"VENONAT@@@",
"VENOMOTH@@",
"DIGLETT@@@",
"DUGTRIO@@@",
"MEOWTH@@@@",
"PERSIAN@@@",
"PSYDUCK@@@",
"GOLDUCK@@@",
"MANKEY@@@@",
"PRIMEAPE@@",
"GROWLITHE@",
"ARCANINE@@",
"POLIWAG@@@",
"POLIWHIRL@",
"POLIWRATH@",
"ABRA@@@@@@",
"KADABRA@@@",
"ALAKAZAM@@",
"MACHOP@@@@",
"MACHOKE@@@",
"MACHAMP@@@",
"BELLSPROUT",
"WEEPINBELL",
"VICTREEBEL",
"TENTACOOL@",
"TENTACRUEL",
"GEODUDE@@@",
"GRAVELER@@",
"GOLEM@@@@@",
"PONYTA@@@@",
"RAPIDASH@@",
"SLOWPOKE@@",
"SLOWBRO@@@",
"MAGNEMITE@",
"MAGNETON@@",
"FARFETCH'D",
"DODUO@@@@@",
"DODRIO@@@@",
"SEEL@@@@@@",
"DEWGONG@@@",
"GRIMER@@@@",
"MUK@@@@@@@",
"SHELLDER@@",
"CLOYSTER@@",
"GASTLY@@@@",
"HAUNTER@@@",
"GENGAR@@@@",
"ONIX@@@@@@",
"DROWZEE@@@",
"HYPNO@@@@@",
"KRABBY@@@@",
"KINGLER@@@",
"VOLTORB@@@",
"ELECTRODE@",
"EXEGGCUTE@",
"EXEGGUTOR@",
"CUBONE@@@@",
"MAROWAK@@@",
"HITMONLEE@",
"HITMONCHAN",
"LICKITUNG@",
"KOFFING@@@",
"WEEZING@@@",
"RHYHORN@@@",
"RHYDON@@@@",
"CHANSEY@@@",
"TANGELA@@@",
"KANGASKHAN",
"HORSEA@@@@",
"SEADRA@@@@",
"GOLDEEN@@@",
"SEAKING@@@",
"STARYU@@@@",
"STARMIE@@@",
"MR.MIME@@@",
"SCYTHER@@@",
"JYNX@@@@@@",
"ELECTABUZZ",
"MAGMAR@@@@",
"PINSIR@@@@",
"TAUROS@@@@",
"MAGIKARP@@",
"GYARADOS@@",
"LAPRAS@@@@",
"DITTO@@@@@",
"EEVEE@@@@@",
"VAPOREON@@",
"JOLTEON@@@",
"FLAREON@@@",
"PORYGON@@@",
"OMANYTE@@@",
"OMASTAR@@@",
"KABUTO@@@@",
"KABUTOPS@@",
"AERODACTYL",
"SNORLAX@@@",
"ARTICUNO@@",
"ZAPDOS@@@@",
"MOLTRES@@@",
"DRATINI@@@",
"DRAGONAIR@",
"DRAGONITE@",
"MEWTWO@@@@",
"MEW@@@@@@@",
"TROPIUS@@@",
"KECLEON@@@",
"CHATOT@@@@",
"PIKIPEK@@@",
"TRUMBEAK@@",
"TOUCANNON@",
"MUNCHLAX@@",
"ROCKRUFF@@",
"LYCANROC@@",
"WINGULL@@@",
"PELIPPER@@",
"CHINGLING@",
"CHIMECHO@@",
"SALANDIT@@",
"SALAZZLE@@",
"FINNEON@@@",
"LUMINEON@@",
"CROBAT@@@@",
"CHINCHOU@@",
"LANTURN@@@",
"PICHU@@@@@",
"CLEFFA@@@@",
"IGGLYBUFF@",
"TOGEPI@@@@",
"TOGETIC@@@",
"TOGEKISS@@",
"AZURILL@@@",
"MAREEP@@@@",
"FLAAFFY@@@",
"AMPHAROS@@",
"BELLOSSOM@",
"MARILL@@@@",
"AZUMARILL@",
"MIME JR.@@",
"POLITOED@@",
"HOPPIP@@@@",
"SKIPLOOM@@",
"JUMPLUFF@@",
"STUNFISK@@",
"SUNKERN@@@",
"SUNFLORA@@",
"LEAFEON@@@",
"GLACEON@@@",
"SYLVEON@@@",
"ESPEON@@@@",
"UMBREON@@@",
"RELICANTH@",
"SLOWKING@@",
"MIMIKYU@@@",
"SPINDA@@@@",
"SKRELP@@@@",
"DRAGALGE@@",
"TRAPINCH@@",
"VIBRAVA@@@",
"FLYGON@@@@",
"TURTONATOR",
"STEELIX@@@",
"WAILMER@@@",
"WAILORD@@@",
"QWILFISH@@",
"SCIZOR@@@@",
"SHUCKLE@@@",
"MAREANIE@@",
"TOXAPEX@@@",
"SANDYGAST@",
"PALOSSAND@",
"SLUGMA@@@@",
"MAGCARGO@@",
"CARVANHA@@",
"SHARPEDO@@",
"CORSOLA@@@",
"REMORAID@@",
"OCTILLERY@",
"MANTYKE@@@",
"MANTINE@@@",
"SKARMORY@@",
"MAGMORTAR@",
"ELECTIVIRE",
"KINGDRA@@@",
"PHANPY@@@@",
"DONPHAN@@@",
"PORYGON2@@",
"PORYGON-Z@",
"LICKILICKY",
"TYROGUE@@@",
"HITMONTOP@",
"SMOOCHUM@@",
"ELEKID@@@@",
"MAGBY@@@@@",
"HAPPINY@@@",
"BLISSEY@@@",
"CUTIEFLY@@",
"RIBOMBEE@@",
"TANGROWTH@",
"RHYPERIOR@",
"MAGNEZONE@",
"MARSHADOW@",
"LUGIA@@@@@",
"HO-OH@@@@@",
"CELEBI@@@@",
"LATIAS@@@@",
"LATIOS@@@@",
"EGG@@@@@@@",
"?????@@@@@"
]
itemNames = [ # from pokeorange/items/item_names.asm
    "",
    "MASTER BALL@",
    "ULTRA BALL@",
    "BRIGHTPOWDER@",
    "GREAT BALL@",
    "# BALL@",
    "TOWN MAP@",
    "SKATEBOARD@",
    "MOON STONE@",
    "ANTIDOTE@",
    "BURN HEAL@",
    "ICE HEAL@",
    "AWAKENING@",
    "PARLYZ HEAL@",
    "FULL RESTORE@",
    "MAX POTION@",
    "HYPER POTION@",
    "SUPER POTION@",
    "POTION@",
    "ESCAPE ROPE@",
    "REPEL@",
    "MAX ELIXER@",
    "FIRE STONE@",
    "THUNDERSTONE@",
    "WATER STONE@",
    "PINKAN BERRY@",
    "HP UP@",
    "PROTEIN@",
    "IRON@",
    "CARBOS@",
    "LUCKY PUNCH@",
    "CALCIUM@",
    "RARE CANDY@",
    "X ACCURACY@",
    "LEAF STONE@",
    "METAL POWDER@",
    "NUGGET@",
    "# DOLL@",
    "FULL HEAL@",
    "REVIVE@",
    "MAX REVIVE@",
    "GUARD SPEC.@",
    "SUPER REPEL@",
    "MAX REPEL@",
    "DIRE HIT@",
    "MASTER ROD@",
    "FRESH WATER@",
    "SODA POP@",
    "LEMONADE@",
    "X ATTACK@",
    "X DEFEND@",
    "X SPEED@",
    "X SPCL ATK@",
    "COIN CASE@",
    "ITEMFINDER@",
    "# FLUTE@",
    "EXP.ALL@",
    "OLD ROD@",
    "GOOD ROD@",
    "SUPER ROD@",
    "PP UP@",
    "PP MAX@",
    "ETHER@",
    "MAX ETHER@",
    "ELIXER@",
    "PINK CURE@",
    "HEART SCALE@",
    "QUICK CLAW@",
    "PECHA BERRY@",
    "SOFT SAND@",
    "SHARP BEAK@",
    "CHERI BERRY@",
    "ASPEAR BERRY@",
    "RAWST BERRY@",
    "POISON BARB@",
    "KING'S ROCK@",
    "PERSIM BERRY@",
    "CHESTO BERRY@",
    "TINYMUSHROOM@",
    "BIG MUSHROOM@",
    "SILVERPOWDER@",
    "AMULET COIN@",
    "CLEANSE TAG@",
    "MYSTIC WATER@",
    "TWISTEDSPOON@",
    "BLACKBELT@",
    "BLACKGLASSES@",
    "PINK BOW@",
    "STICK@",
    "SMOKE BALL@",
    "NEVERMELTICE@",
    "MAGNET@",
    "LUM BERRY@",
    "PEARL@",
    "BIG PEARL@",
    "EVERSTONE@",
    "SPELL TAG@",
    "GRAPEFRUIT@",
    "GS BALL@",
    "MIRACLE SEED@",
    "THICK CLUB@",
    "FOCUS BAND@",
    "ENERGYPOWDER@",
    "ENERGY ROOT@",
    "HEAL POWDER@",
    "REVIVAL HERB@",
    "HARD STONE@",
    "LUCKY EGG@",
    "STARDUST@",
    "STAR PIECE@",
    "CHARCOAL@",
    "BERRY JUICE@",
    "SCOPE LENS@",
    "METAL COAT@",
    "DRAGON FANG@",
    "LEFTOVERS@",
    "LEPPA BERRY@",
    "DRAGON SCALE@",
    "HEAVY BALL@",
    "LEVEL BALL@",
    "LURE BALL@",
    "FAST BALL@",
    "LIGHT BALL@",
    "FRIEND BALL@",
    "MOON BALL@",
    "LOVE BALL@",
    "SUN STONE@",
    "POLKADOT BOW@",
    "UP-GRADE@",
    "ORAN BERRY@",
    "SITRUS BERRY@",
    "SQUIRTBOTTLE@",
    "CONTEST BALL@",
    "IMAKUNI?CARD@",
    "SACRED ASH@",
    "SILVER WING@",
    "RAINBOW WING@",
    "SHINY STONE@",
    "LINK CABLE@",
    "MORO TROPHY@",
    "DUBIOUS DISC@",
    "SHINY CHARM@",
    "SOUL DEW@",
    "DIVE BALL@",
    "HEAL BALL@",
    "DUSK BALL@",
    "FLOWER MAIL@",
    "SURF MAIL@",
    "LITEBLUEMAIL@",
    "PORTRAITMAIL@",
    "LOVELY MAIL@",
    "EON MAIL@",
    "MORPH MAIL@",
    "BLUESKY MAIL@",
    "MUSIC MAIL@",
    "MIRAGE MAIL@",
    "X SPCL DEF@",
    "ICE STONE@",
    "QUICK POWDER@",
    "MAGMARIZER@",
    "ELECTIRIZER@",
    "PROTECTOR@",
    "SALVEYO WEED@",
    "CAT STATUE@",
    "SHELL BOX@",
    "ELECTRIC ORB@",
    "FIRE ORB@",
    "ICE ORB@",
    "TM01@",
    "TM02@",
    "TM03@",
    "TM04@",
    "TM05@",
    "TM06@",
    "TM07@",
    "TM08@",
    "TM09@",
    "TM10@",
    "TM11@",
    "TM12@",
    "TM13@",
    "TM14@",
    "TM15@",
    "TM16@",
    "TM17@",
    "TM18@",
    "TM19@",
    "TM20@",
    "TM21@",
    "TM22@",
    "TM23@",
    "TM24@",
    "TM25@",
    "TM26@",
    "TM27@",
    "TM28@",
    "TM29@",
    "TM30@",
    "TM31@",
    "TM32@",
    "TM33@",
    "TM34@",
    "TM35@",
    "TM36@",
    "TM37@",
    "TM38@",
    "TM39@",
    "TM40@",
    "TM41@",
    "TM42@",
    "TM43@",
    "TM44@",
    "TM45@",
    "TM46@",
    "TM47@",
    "TM48@",
    "TM49@",
    "TM50@",
    "HM01@",
    "HM02@",
    "HM03@",
    "HM04@",
    "HM05@",
    "HM06@",
    "HM07@"
]
landmarkConstants = [ # from pokeorange/constants/landmark_constants.asm
    "SPECIAL_MAP",
    "VALENCIA_ISLAND",
    "ROUTE_49",
    "TANGELO_ISLAND",
    "ROUTE_50",
    "ROUTE_51",
    "TANGELO_JUNGLE",
    "ROUTE_52",
    "MIKAN_ISLAND",
    "ROUTE_53",
    "ROUTE_54",
    "MANDARIN_NORTH",
    "SUNBURST_ISLAND",
    "ROUTE_55",
    "CRYSTAL_CAVE",
    "PINKAN_ISLAND",
    "ROUTE_56",
    "FUKUHARA_4",
    "KINNOW_ISLAND",
    "ROUTE_57",
    "UNNAMED_ISLAND_1",
    "ROUTE_58",
    "NAVEL_ISLAND",
    "MT_NAVEL",
    "GRAPEFRUIT",
    "ROUTE_59",
    "MORO_ISLAND",
    "ROUTE_60",
    "WRECKED_SHIP",
    "GOLDEN_ISLAND",
    "ROUTE_61",
    "MURCOTT_ISLAND",
    "UNNAMED_ISLAND_2",
    "ROUTE_62",
    "MANDARIN_DESERT",
    "TROVITOPOLIS",
    "TROVITA_ISLAND",
    "CLEOPATRA_ISLAND",
    "ROUTE_63",
    "ASCORBIA_ISLAND",
    "ROUTE_64",
    "ROUTE_65",
    "BUTWAL_ISLAND",
    "ROUTE_66",
    "KUMQUAT_ISLAND",
    "ROUTE_67",
    "RIND_ISLAND",
    "ROUTE_68",
    "UNNAMED_ISLAND_3",
    "ROUTE_69",
    "VICTORY_ROAD",
    "PUMMELO_ISLAND",
    "ROUTE_70",
    "TARROCO_ISLAND",
    "ROUTE_71",
    "HAMLIN_ISLAND",
    "HAMLIN_FIELDS",
    "SHAMOUTI_ISLAND",
    "FIRE_ISLAND",
    "ICE_ISLAND",
    "LIGHTNING_ISLAND",
    "VERMILION_CITY",
    "ROUTE_11",
    "ROUTE_12",
    "ROUTE_13",
    "ROUTE_14",
    "ROUTE_15",
    "FUCHSIA_CITY",
    "SAFARI_ZONE",
    "ROUTE_19",
    "ROUTE_20",
    "SEAFOAM_ISLANDS",
    "CINNABAR_ISLAND",
    "CINNABAR_VOLCANO",
    "ROUTE_21",
    "PALLET_TOWN",
    "CINNABAR_SEA",
    "SAYDA_ISLAND",
    "KANTO_SEA_1",
    "CAMOMILE_ISLAND",
    "VERMILION_SEA",
    "KANTO_SEA_2",
    "CHRYSANTHEMUM",
    "METALLICA_ISLAND",
    "KANTO_SEA_3",
    "WISTERIA_TOWN",
    "HUTBER_CITY",
    "PORTA_VISTA",
    "ACAPULCO_TOWN",
    "NEW_ISLAND",
    "RAINBOW_ISLAND",
    "FAST_SHIP"
]
moveNames = [ # from pokeorange/battle/move_names.asm
    "",
    "SHADOW CLAW@",
    "KARATE CHOP@",
    "DOUBLESLAP@",
    "COMET PUNCH@",
    "POISON JAB@",
    "PAY DAY@",
    "FIRE PUNCH@",
    "ICE PUNCH@",
    "THUNDERPUNCH@",
    "SCRATCH@",
    "BULLET SEED@",
    "GUILLOTINE@",
    "DRAGON PULSE@",
    "SWORDS DANCE@",
    "CUT@",
    "GUST@",
    "WING ATTACK@",
    "WHIRLWIND@",
    "FLY@",
    "DARK PULSE@",
    "SLAM@",
    "VINE WHIP@",
    "STOMP@",
    "DOUBLE KICK@",
    "ZEN HEADBUTT@",
    "GIGA IMPACT@",
    "FLASH CANNON@",
    "SAND-ATTACK@",
    "HEADBUTT@",
    "HORN ATTACK@",
    "FURY ATTACK@",
    "HORN DRILL@",
    "TACKLE@",
    "BODY SLAM@",
    "WRAP@",
    "TAKE DOWN@",
    "THRASH@",
    "DOUBLE-EDGE@",
    "TAIL WHIP@",
    "POISON STING@",
    "TWINEEDLE@",
    "PIN MISSILE@",
    "LEER@",
    "BITE@",
    "GROWL@",
    "ROAR@",
    "SING@",
    "SUPERSONIC@",
    "SONICBOOM@",
    "DISABLE@",
    "ACID@",
    "EMBER@",
    "FLAMETHROWER@",
    "MIST@",
    "WATER GUN@",
    "HYDRO PUMP@",
    "SURF@",
    "ICE BEAM@",
    "BLIZZARD@",
    "PSYBEAM@",
    "BUBBLEBEAM@",
    "AURORA BEAM@",
    "HYPER BEAM@",
    "PECK@",
    "DRILL PECK@",
    "SUBMISSION@",
    "LOW KICK@",
    "COUNTER@",
    "SEISMIC TOSS@",
    "STRENGTH@",
    "ABSORB@",
    "PLAY ROUGH@",
    "LEECH SEED@",
    "GROWTH@",
    "RAZOR LEAF@",
    "SOLARBEAM@",
    "POISONPOWDER@",
    "STUN SPORE@",
    "SLEEP POWDER@",
    "PETAL DANCE@",
    "STRING SHOT@",
    "DRAGON RAGE@",
    "FIRE SPIN@",
    "THUNDERSHOCK@",
    "THUNDERBOLT@",
    "THUNDER WAVE@",
    "THUNDER@",
    "ROCK THROW@",
    "EARTHQUAKE@",
    "FISSURE@",
    "DIG@",
    "TOXIC@",
    "CONFUSION@",
    "PSYCHIC@",
    "HYPNOSIS@",
    "POWER GEM@",
    "AGILITY@",
    "QUICK ATTACK@",
    "RAGE@",
    "TELEPORT@",
    "NIGHT SHADE@",
    "MIMIC@",
    "SCREECH@",
    "DOUBLE TEAM@",
    "RECOVER@",
    "HARDEN@",
    "MINIMIZE@",
    "SMOKESCREEN@",
    "CONFUSE RAY@",
    "WITHDRAW@",
    "DEFENSE CURL@",
    "BARRIER@",
    "LIGHT SCREEN@",
    "HAZE@",
    "REFLECT@",
    "FOCUS ENERGY@",
    "ROCK BLAST@",
    "METRONOME@",
    "MIRROR MOVE@",
    "SELFDESTRUCT@",
    "EGG BOMB@",
    "LICK@",
    "SMOG@",
    "SLUDGE@",
    "SHADOW BONE@",
    "FIRE BLAST@",
    "WATERFALL@",
    "CLAMP@",
    "SWIFT@",
    "SIGNAL BEAM@",
    "SPIKE CANNON@",
    "ACCELEROCK@",
    "AMNESIA@",
    "DIVE@",
    "SOFTBOILED@",
    "HI JUMP KICK@",
    "GLARE@",
    "DREAM EATER@",
    "POISON GAS@",
    "BARRAGE@",
    "LEECH LIFE@",
    "SKETCH@",
    "SEED BOMB@",
    "TRANSFORM@",
    "BUBBLE@",
    "DIZZY PUNCH@",
    "SPORE@",
    "FLASH@",
    "MIST BALL@",
    "SPLASH@",
    "ACID ARMOR@",
    "CRABHAMMER@",
    "EXPLOSION@",
    "FURY SWIPES@",
    "BONEMERANG@",
    "REST@",
    "ROCK SLIDE@",
    "HYPER FANG@",
    "FACADE@",
    "CONVERSION@",
    "TRI ATTACK@",
    "SUPER FANG@",
    "SLASH@",
    "SUBSTITUTE@",
    "ROCK CLIMB@",
    "TRIPLE KICK@",
    "THIEF@",
    "SHELL TRAP@",
    "LUSTER PURGE@",
    "VENOSHOCK@",
    "FLAME WHEEL@",
    "EARTH POWER@",
    "CURSE@",
    "FLAIL@",
    "CONVERSION2@",
    "AEROBLAST@",
    "COTTON SPORE@",
    "REVERSAL@",
    "NASTY PLOT@",
    "HAIL@",
    "PROTECT@",
    "MACH PUNCH@",
    "SCARY FACE@",
    "FAINT ATTACK@",
    "SWEET KISS@",
    "BELLY DRUM@",
    "SLUDGE BOMB@",
    "MUD-SLAP@",
    "OCTAZOOKA@",
    "SPIKES@",
    "ZAP CANNON@",
    "FORESIGHT@",
    "DESTINY BOND@",
    "PERISH SONG@",
    "ICY WIND@",
    "POWERUPPUNCH@",
    "BONE RUSH@",
    "LOCK-ON@",
    "OUTRAGE@",
    "SANDSTORM@",
    "GIGA DRAIN@",
    "ENDURE@",
    "CHARM@",
    "ROLLOUT@",
    "FALSE SWIPE@",
    "SWAGGER@",
    "WATER PULSE@",
    "SPARK@",
    "BUG BITE@",
    "STEEL WING@",
    "MEAN LOOK@",
    "ATTRACT@",
    "SLEEP TALK@",
    "HEAL BELL@",
    "RETURN@",
    "ASTONISH@",
    "BOUNCE@",
    "SAFEGUARD@",
    "SPECTRATHIEF@",
    "SACRED FIRE@",
    "MAGNITUDE@",
    "DYNAMICPUNCH@",
    "WOOD HAMMER@",
    "DRAGONBREATH@",
    "BATON PASS@",
    "ENCORE@",
    "PURSUIT@",
    "RAPID SPIN@",
    "SWEET SCENT@",
    "IRON TAIL@",
    "METAL CLAW@",
    "VITAL THROW@",
    "MORNING SUN@",
    "SYNTHESIS@",
    "MOONLIGHT@",
    "VOLT TACKLE@",
    "CROSS CHOP@",
    "DRAGON TAIL@",
    "RAIN DANCE@",
    "SUNNY DAY@",
    "CRUNCH@",
    "MIRROR COAT@",
    "AERIAL ACE@",
    "EXTREMESPEED@",
    "ANCIENTPOWER@",
    "SHADOW BALL@",
    "FUTURE SIGHT@",
    "ROCK SMASH@",
    "WHIRLPOOL@",
    "PSYSTRIKE@",
    "MOONBLAST@",
    "FAIRY WIND@",
    "DAZZLINGLEAM@",
    "SHADOW SNEAK@",
    "STRUGGLE@"
]

def read_chunks(f, length):
    while True:
        data = f.read(length)
        if not data: break
        yield data

with open(sys.argv[1], "rb") as savFile:
    save = [struct_unpack(chunk) for chunk in read_chunks(savFile, struct_len)]
    print("Read", len(save), "Pokemon from Active Box.")
    for idx, x in enumerate(save):
        tempDict = {}
        tempDict["mon_species"] = pokemonNames[int.from_bytes(save[idx][0], byteorder="big")]
        tempDict["item"] = itemNames[int.from_bytes(save[idx][1], byteorder="big")]
        tempDict["move1"] = moveNames[int.from_bytes(save[idx][2], byteorder="big")]
        tempDict["move2"] = moveNames[int.from_bytes(save[idx][3], byteorder="big")]
        tempDict["move3"] = moveNames[int.from_bytes(save[idx][4], byteorder="big")]
        tempDict["move4"] = moveNames[int.from_bytes(save[idx][5], byteorder="big")]
        tempDict["id"] = int.from_bytes(save[idx][6], byteorder="big")
        tempDict["caughtLocation"] = landmarkConstants[int.from_bytes(save[idx][22], byteorder="big") - 1]
        boxPokemon.append(tempDict)
    print(json.dumps(boxPokemon, sort_keys=True, indent=4))